name: game_anak_soleh
description: "Game edukasi Islami 2D ala platformer untuk anak usia 3-7 tahun."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  flame_audio: ^2.10.7
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg/
    - assets/images/ground/
    - assets/images/platform/
    - assets/images/obstacle/
    - assets/images/characters/
    - assets/images/buildings/
    - assets/images/items/
    - assets/images/scenery/
    - assets/sounds/sfx/
    - assets/sounds/music/
